language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t maracartman/node-test -f ./Dockerfile.dev .

script:
  - docker run -e CI=true maracartman/node-test npm run test -- --coverage

after_success:
  - docker build -t maracartman/ml-server .
  # Log In into Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push maracartman/ml-server
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: ml-searcher
  env: MlSearcher-env
  bucket_name: elasticbeanstalk-us-west-1-768964238245
  bucket_path: docker-ml
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY